version: "3"

services:
  neon-tracer:
    container_name: neon-tracer
    hostname: neon-tracer
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: neon=debug,metrics=debug
      LISTEN_ADDR: 0.0.0.0:8250
      WEB3_PROXY: https://devnet.neonevm.org/solana
      METRICS_IP: 0.0.0.0
      METRICS_PORT: 9292
      NEON_TOKEN_MINT: HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU
      NEON_CHAIN_ID: 111
      MONITORING_INTERVAL_SEC: 1
      NEON_API_URL: http://neon-api:8080
      NEON_DB_CLICKHOUSE_URLS: ${DB_CLICKHOUSE_URLS}
      NEON_DB_INDEXER_HOST: ${DB_INDEXER_HOST}
      NEON_DB_INDEXER_PORT: ${DB_INDEXER_PORT}
      NEON_DB_INDEXER_DATABASE: ${DB_INDEXER_DATABASE}
      NEON_DB_INDEXER_USER: ${DB_INDEXER_USER}
      NEON_DB_INDEXER_PASSWORD: ${INDEXER_DB_PASSWORD}
    image: neonlabsorg/neon-tracer:${BUILDKITE_COMMIT:-latest}
    expose:
      - "8250"
    ports:
      - "127.0.0.1:8250:8250"
      - "127.0.0.1:9292:9292"
    networks:
      - net
    depends_on:
      neon-api:
        condition: service_started

  neon-api:
    restart: unless-stopped
    container_name: neon-api
    hostname: neon-api
    command: /opt/neon-api -H 0.0.0.0:8080
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: neon=debug
      NEON_API_LISTENER_ADDR: 0.0.0.0:8080
      SOLANA_URL: ${SOLANA_URL}
      EVM_LOADER: eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU
      NEON_TOKEN_MINT: 89dre8rZjLNft7HoupGiyxu3MNftR577ZYu8bHe2kK7g
      NEON_CHAIN_ID: 245022926
      COMMITMENT: confirmed
      NEON_DB_CLICKHOUSE_URLS: ${DB_CLICKHOUSE_URLS}
      NEON_DB_INDEXER_HOST: ${DB_INDEXER_HOST}
      NEON_DB_INDEXER_PORT: ${DB_INDEXER_PORT}
      NEON_DB_INDEXER_DATABASE: ${DB_INDEXER_DATABASE}
      NEON_DB_INDEXER_USER: ${DB_INDEXER_USER}
      NEON_DB_INDEXER_PASSWORD: ${INDEXER_DB_PASSWORD}
      KEYPAIR: /opt/id.json
      FEEPAIR: /opt/id.json
    image: neonlabsorg/evm_loader:f24777388ec51dd28da3481db7d5c019808c5ad1
    expose:
      - "8080:8080"
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
      - ./ci/id.json:/opt/id.json

  neon-rpc:
    container_name: neon-rpc
    hostname: neon-rpc
    image: neonlabsorg/neon-rpc:${BUILDKITE_COMMIT:-latest}
    expose:
      - "9090"
    networks:
      - net
    ports:
      - 127.0.0.1:9090:9090
    depends_on:
      neon-tracer:
        condition: service_started
  
  neon-tracer-test:
    container_name: neon-tracer-test
    hostname: neon-tracer-test
    image: neonlabsorg/neon-tracer-test:${BUILDKITE_COMMIT:-latest}
    networks:
      - net
    depends_on:
      neon-rpc:
        condition: service_started
        
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - net
    ports:
      - "127.0.0.1:9393:9090"
    depends_on:
      neon-rpc:
        condition: service_started

networks:
  net:

